on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Run lint
        run: ./bin/ameba
      - name: Run format
        run: crystal tool format --check
      - name: Run build
        run: shards build --release
      - name: Run chmod
        run: chmod +x bin/castblock
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: binary
          path: bin/castblock
